services:
  proxy:
    container_name: rijks-proxy
    restart: always
    image: ${IMAGE_REGISTRY:-ghcr.io}/magwoo/rijks-proxy:latest
    build:
      context: ../
      dockerfile: proxy/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./data/caddy:/data/caddy\
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
